server:
    port: 9192
    error:
        include-message: always

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/chatop
        username: root
        password: test
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        open-in-view: true

bezkoder:
    app:
        jwtSecret: ======================BezKoder=Spring===========================
        jwtExpirationMs: 86400000
