server:
    port: 9192
    error:
        include-message: always

spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        open-in-view: true

bezkoder:
    app:
        jwtSecret: ${BEZKODER_APP_JWT_SECRET}
        jwtExpirationMs: ${BEZKODER_APP_JWT_EXPIRATION_MS}

store:
    uploadDir: ${STORE_UPLOAD_DIR:uploads}
